# Generated by Django 4.1.7 on 2023-03-13 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proizvodstvo', '0012_alter_favouriteadv_fav_adv'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stroka', models.TextField(default='')),
                ('count', models.IntegerField()),
            ],
            options={
                'verbose_name': 'товар',
                'verbose_name_plural': 'товары',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_order', models.TextField()),
                ('description', models.TextField(default='')),
                ('status', models.TextField(choices=[("<class 'proizvodstvo.models.OrderStatusChoices.Meta'>", 'Meta'), ('OPEN', 'Открыто'), ('CLOSED', 'Закрыто'), ('SERVIE', 'Обслуживается')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('servise_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
            },
        ),
        migrations.RemoveField(
            model_name='favouriteadv',
            name='fav_adv',
        ),
        migrations.RemoveField(
            model_name='favouriteadv',
            name='user',
        ),
        migrations.DeleteModel(
            name='Advertisement',
        ),
        migrations.DeleteModel(
            name='FavouriteAdv',
        ),
        migrations.AddField(
            model_name='items',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proizvodstvo.orders'),
        ),
    ]
