# Generated by Django 4.1.7 on 2023-03-13 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proizvodstvo', '0013_items_orders_remove_favouriteadv_fav_adv_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='servise_at',
            new_name='service_at',
        ),
    ]
